### ISSUE TITLE
缺少game.json/project.config.json的目录

### ISSUE THREAD

**Issue by bofeiw** [xiandew/BubbleSpinner#1]

**Comment by bofeiw** [comment]
<img width="522" alt="2019-03-08 2 13 50" src="https://user-images.githubusercontent.com/34177142/54005151-6d925e00-41ac-11e9-9973-cd5411c7109f.png">

**Comment by xiandew** [comment]
It was intended for hiding the appid. No big changes made to that file so you can copy that directly from the sample game codes.
